services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discordjs-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # depends_on:
      # - db

#   db:
#     image: postgres:17-alpine
#     container_name: discordjs-db
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: discordbot
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data: 