name: Build

permissions:
  contents: read

on:
  push:
    branches: [main]

  pull_request:

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allow the workflow to be re-used in other workflows
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.13

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint
